---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuseml-core
  namespace: fuseml-core
---
# Give the admin rights to ServiceAccount, so it can
# delete various resources forming FuseML applications
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fuseml-core-admin-binding
  namespace: fuseml-workloads
subjects:
  - kind: ServiceAccount
    name: fuseml-core
    namespace: fuseml-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuseml-core-data
  namespace: fuseml-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseml-core
  namespace: fuseml-core
  labels:
    app.kubernetes.io/name: fuseml-core
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fuseml-core
  replicas: 1
  strategy:
    # state is persisted locally and doesn't support shared (i.e. RWX) storage mode
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fuseml-core
    spec:
      serviceAccountName: fuseml-core
      containers:
      - name: fuseml-core
        image: ghcr.io/fuseml/fuseml-core:v0.2.1
        imagePullPolicy: Always
        env:
          - name: GITEA_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                key: GITEA_ADMIN_USERNAME
                name: fuseml-core-gitea
          - name: GITEA_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: GITEA_ADMIN_PASSWORD
                name: fuseml-core-gitea
          - name: GITEA_URL
            valueFrom:
              configMapKeyRef:
                key: GITEA_URL
                name: config-fuseml-core
          - name: TEKTON_DASHBOARD_URL
            valueFrom:
              configMapKeyRef:
                key: TEKTON_DASHBOARD_URL
                name: config-fuseml-core
        ports:
        - containerPort: 80
        volumeMounts:
        - name: value-storage
          mountPath: /data
      volumes:
      - name: value-storage
        persistentVolumeClaim:
          claimName: fuseml-core-data
---        
apiVersion: v1
kind: Service
metadata:
  name: fuseml-core
  namespace: fuseml-core
  labels:
    app.kubernetes.io/name: fuseml-core
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: fuseml-core
