name: Release-pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Branch
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=BRANCH_NAME::$branch"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Build FuseML
        run: |
          make release
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: "false"
          onlyLastTag: "true"
          stripGeneratorNotice: "true"
          issuesWoLabels: "true"
          stripHeaders: "true"
      - name: Release FuseML
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}